name: Sync Upstream

on:
  schedule:
    - cron: '*/5 * * * *'  
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: stockimen/clashfree  # 替换为你的 GitHub 用户名和仓库名
        ref: main  # 替换为你的主分支
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Pull upstream changes
      run: git pull upstream

