name: Sync Upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 使用最新的 v3 版本
      with:
        repository: stockimen/clashfree  # 替换为你的 GitHub 用户名和仓库名
        ref: main  # 替换为你的主分支
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add upstream remote
      run: git remote add upstream https://github.com/aiboboxx/clashfree.git || echo "Upstream already exists"

    - name: Fetch upstream changes
      run: git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout main
        git merge upstream/main --no-ff  # 创建合并提交
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
